### ISSUE TITLE
Package.load() error due to missing config.yaml

### ISSUE THREAD

**Issue by HeidiSeibold** [frictionlessdata/datapackage-r#11]
I am following the instructions in the [vignette](https://github.com/frictionlessdata/datapackage-r/blob/master/vignettes/creating_data_packages_in_r.Rmd), but I get an error:

```
> library("datapackage.r")
> dataPackage = Package.load()
Error in config::get("DEFAULT_DATA_PACKAGE_PROFILE", file = "config.yaml") : 
  Config file config.yaml not found in current working directory or parent directories
```

Could you add instructions on how to add the config.yaml? Thanks :smiley_cat:

**Comment by kleanthisk10** [comment]
Hello, currently you have to add the [config.yml](https://github.com/frictionlessdata/datapackage-r/blob/master/config.yml) and [config.yaml](https://github.com/frictionlessdata/datapackage-r/blob/master/config.yaml) files manually to your working directory to resolve the issue.
(There is already issue #9)

**Comment by HeidiSeibold** [comment]
Ok, that helped :)

Thanks!

**Comment by lanec-unifesspa** [comment]
I can confirm the bug; moreover, the links provided in the comment are not available.

**Comment by kleanthisk10** [comment]
@lanec-unifesspa the links are removed because the bug fixed, you should try re install both [tableschema.r](https://github.com/frictionlessdata/tableschema-r) and [datapackage.r](https://github.com/frictionlessdata/datapackage-r) libraries.
thank you
