### ISSUE TITLE
dataPackage$save() requires creating a directory 

### ISSUE THREAD

**Issue by HeidiSeibold** [frictionlessdata/datapackage-r#12]
I run into another error when running the [vignette](https://github.com/frictionlessdata/datapackage-r/blob/master/vignettes/creating_data_packages_in_r.Rmd) example:

```
> dataPackage$save('example_data')
Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") :
  cannot open file 'example_data/package.json': No such file or directory
```

when I manually create the folder `example_data`, it works.

**Comment by kleanthisk10** [comment]
The 'example_data' refers to the target folder, where you want to save the datapackage, as it's documented in [dataPackage$save](https://github.com/frictionlessdata/datapackage-r#packagesavetarget)

**Comment by HeidiSeibold** [comment]
I understand. Then I would suggest to either allow for `dataPackage$save` to create the folder if it doesn't exist or to use `dataPackage$save('.')` in the vignette so it runs without errors for people who just want to see how it works

**Comment by kleanthisk10** [comment]
`dataPackage$save` updated and you can create a folder if it doesn't exists.  `dataPackage$save('.')` was working and before the update.
