### ISSUE TITLE
Error with dataPackage$infer

### ISSUE THREAD

**Issue by lanec-unifesspa** [frictionlessdata/datapackage-r#14]
Following the vignettes, at the first attempt to run the command jsonlite::toJSON(dataPackage$infer('csv'), pretty=TRUE), I ran into the following error message:

> Error in private$getTable_() : attempt to apply non-function

This is in RStudio Version 1.1.419, running on Windows 10.

**Comment by kleanthisk10** [comment]
@lanec-unifesspa yes indeed, updates of [future](https://CRAN.R-project.org/package=future) package  affected the [datapackage.r](https://github.com/frictionlessdata/datapackage-r) and [tableschema.r](https://github.com/frictionlessdata/tableschema-r) packages. 

Can you please re-install and try again?
Thank you!
