### ISSUE TITLE
Publish datapackage-r on CRAN

### ISSUE THREAD

**Issue by serahkiburu** [frictionlessdata/datapackage-r#17]
https://discuss.okfn.org/t/is-getting-tableschema-r-on-cran-a-goal-for-that-repo-package/7249

**Comment by serahkiburu** [comment]
Thanks for getting this datapackage-r [published on C-RAN](https://cran.r-project.org/src/contrib/Archive/DataPackageR/), @kleanthisk10 !

**Comment by serahkiburu** [comment]
Hi @kleanthisk10, just noticed that [DataPackageR, referenced in my comment above](https://cran.r-project.org/web/packages/DataPackageR/index.html),  is indeed a different package, developed by the ROpenSci team.

Reopening this issue.

**Comment by kleanthisk10** [comment]
On CRAN now!
https://CRAN.R-project.org/package=datapackage.r

**Comment by serahkiburu** [comment]
Fantastic!
