### ISSUE TITLE
Releasing version 1 on CRAN

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-r#19]
# Overview

Hi @kleanthisk10 I think it makes sense to release v1 of this package on CRAN taking into account that there is no active development of new features at the moment.

WDYT?

PS.
At the moment, there is a problem with builds - https://travis-ci.org/frictionlessdata/datapackage-r

**Comment by kleanthisk10** [comment]
Hello @roll  do you mean updating/improving the code content according with the e.g. js implementation?

**Comment by roll** [comment]
@kleanthisk10 
I mean just bumping the version

**Comment by kleanthisk10** [comment]
@roll i plan on updating the functions according to the js version in next months.

**Comment by roll** [comment]
@kleanthisk10 
It's great if you're willing to do so :+1: 

But anyway feel free to release v1 of the lib if there is something not ready/you don't have enough time (and an issue is created).

**Comment by kleanthisk10** [comment]
Done! [https://cran.r-project.org/package=datapackage.r](url)
