### ISSUE TITLE
Travis builds fail

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-r#20]
# Overview

At the moment, builds on Travis fails with an error I don't understand - https://travis-ci.org/frictionlessdata/datapackage-r

---

Please preserve this line to notify the @frictionlessdata/r team

**Comment by roll** [comment]
@kleanthisk10 
Could you please take a look at it if you have some time..

**Comment by kleanthisk10** [comment]
Yes of course!

**Comment by roll** [comment]
Thanks!
