### ISSUE TITLE
test misspecified?

### ISSUE THREAD

**Issue by reikoch** [frictionlessdata/datapackage-r#22]
# Overview

For me test 'mixed' from test-package.R fails with:

    Error in value[[3L]](cond) :
    Not resolved Pointer URI "#/dialects/main" for resource[[dialect]]

Is maybe `data-resource-dereference.json` containing not the right thing?

    {
    "name": "name",
    "data": "data",
    "schema": "table-schema.json",
    "dialect": "#/dialects/main",
    "dialects": {
        "main": {"delimiter": ","}
    }
}

---

Please preserve this line to notify @kleanthisk10 (lead of this repository)

**Comment by kleanthisk10** [comment]
Can you provide more details with your session info? 
You could try reinstalling the package using 
```
devtools::install_github("frictionlessdata/datapackage-r")
```

**Comment by reikoch** [comment]
Yes, this works now
