### ISSUE TITLE
Support foreign key checks and dereferencing

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-r#3]
# Overview

> This issue is not a part of first iteration of work and created for a future implementation if possible

See - https://github.com/frictionlessdata/datapackage-js#foreign-keys

**Comment by kleanthisk10** [comment]
Is this issue referring to these functions?

- https://github.com/frictionlessdata/datapackage-r/blob/master/R/helpers.R#L350
- https://github.com/frictionlessdata/datapackage-r/blob/master/R/helpers.R#L366

Where applied in this section:
- https://github.com/frictionlessdata/datapackage-r/blob/master/R/resource.R#L422

And the new tests:
- https://github.com/frictionlessdata/datapackage-r/blob/master/tests/testthat/test-resource.R#L271 
- https://github.com/frictionlessdata/datapackage-r/blob/master/tests/testthat/test-resource.R#L303
- https://github.com/frictionlessdata/datapackage-r/blob/master/tests/testthat/test-resource.R#L333
- https://github.com/frictionlessdata/datapackage-r/blob/master/tests/testthat/test-resource.R#L363
- https://github.com/frictionlessdata/datapackage-r/blob/master/tests/testthat/test-resource.R#L669
- https://github.com/frictionlessdata/datapackage-r/blob/master/tests/testthat/test-resource.R#L648
- https://github.com/frictionlessdata/datapackage-r/blob/master/tests/testthat/test-resource.R#L678

**Comment by roll** [comment]
Hi @kleanthisk10, sorry it's hard for me to understand R code but the issue is about - https://github.com/frictionlessdata/datapackage-js#working-with-foreign-keys

**Comment by kleanthisk10** [comment]
Yes it's supported!

**Comment by roll** [comment]
@kleanthisk10 
awesome :+1:
