### ISSUE TITLE
Support datapackage identifier spec

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-r#4]
# Overview

> This issue is not a part of first iteration of work and created for a future implementation if possible

Specification - http://dataprotocols.org/data-package-identifier/

**Comment by kleanthisk10** [comment]
@roll the link of specification [http://dataprotocols.org/data-package-identifier/](url) is not working

**Comment by roll** [comment]
@kleanthisk10 
I would close it for now. I'm not sure the protocol is ready to be implemented
