### ISSUE TITLE
Package does not build because of malformed name and maintainer

### ISSUE THREAD

**Issue by HeidiSeibold** [frictionlessdata/datapackage-r#5]
I just checked out the repo and then tried building the R package:

```
$ R CMD build datapackage-r/
* checking for file ‘datapackage-r/DESCRIPTION’ ... OK
* preparing ‘datapackage-r’:
* checking DESCRIPTION meta-information ... ERROR
Malformed package name

Malformed maintainer field.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

See https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file for help.
I'd be willing to create a pull request, but I don't know what you want to name the package and who the maintainter is.

The problem leads to failing installation as described on http://okfnlabs.org/blog/2016/07/14/using-data-packages-with-r.html

**Comment by kleanthisk10** [comment]
Do you still have problem with this?

**Comment by HeidiSeibold** [comment]
Nope, will close this now :)

**Comment by kashiff007** [comment]
I am struggling with same error. Can you please help?

My seed file:
```
Package: BSgenome.Aiptasia.CC7
Title: Full genome sequences for Aiptasia var. CC7 (version 1).
Description: Full genome sequences for Aiptasia var. CC7 (version 1) and stored in Aiptasia genome browser.
Version: 1.0.
organism: Aiptasia var. CC7 (version 1).
common_name: Aiptasia
provider: Manuel Lab
provider_version: v1
release_date: 2016
release_name: Aiptasia.CC7
source_url: http://aiptasia.reefgenomics.org/download/
organism_biocview: Aiptasia.CC7
BSgenomeObjname: Aiptasia.CC7
SrcDataFiles: Aiptasia.CC7.2bit from http://hgdownload.soe.ucsc.edu/goldenPath/musFur1/bigZips/
seqs_srcdir: /home/nawazk/KAUST_Projects/Aiptasia_epigenetic_analysis/results/UMR_identification/Aiptasia_CC7/seqs
seqfile_name: Aiptasia.CC7.2bit
```
I placed a genome file Aiptasia.CC7.2bit in /home/nawazk/KAUST_Projects/Aiptasia_epigenetic_analysis/results/UMR_identification/Aiptasia_CC7/seqs folder         
Do I need to place some more files inside this folder? Is source_url link also important?

Thanks

**Comment by kleanthisk10** [comment]
@kashiff007 what are you trying to do? this issue concerns an error when building "datapackage.r" package (library) and it's fixed.
