### ISSUE TITLE
Error in creating data package + inferring schema

### ISSUE THREAD

**Issue by serahkiburu** [frictionlessdata/datapackage-r#9]
Hi @kleanthisk10 , I get the following errors:

- in running `dataPackage = Package.load()`

I get

```r
Error in config::get("DEFAULT_MISSING_VALUES") : 
  Config file config.yml not found in current working directory or parent directories
```

- in inferring a schema 

 ```r
filepath = ''
schema = tableschema.r::infer(filepath)
```

I get

```r
Error in config::get("DEFAULT_MISSING_VALUES") : 
  Config file config.yml not found in current working directory or parent directories
```

I have to manually add the [config.yml](https://github.com/frictionlessdata/datapackage-r/blob/master/config.yml) and [config.yaml](https://github.com/frictionlessdata/datapackage-r/blob/master/config.yaml) files manually to my working directory to resolve the issue.

**Comment by kleanthisk10** [comment]
Hello @serahrono can you please re-install both [datapackage.r](https://github.com/frictionlessdata/datapackage-r) and [tableschema.r](https://github.com/frictionlessdata/tableschema-r) and try again? I think i fixed this issue.
